AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Dynamically generated password.
      GenerateSecretString:
        SecretStringTemplate: '{"username":"Zealen"}'
        GenerateStringKey: password
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Notification
          Value: Secret
  MessageStorage:
    Type: 'AWS::S3::Bucket'
  MessageHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/messages
      Handler: messageHandler.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - SESCrudPolicy:
            IdentityName: "fall_back_up@hotmail.com"
        - PolicyName: 'snspub'
            Version: '2012-10-17'
            Statement: 
            - Effect: Allow
            Action: 'sns:Publish'
            Resource: *
            
        - S3FullAccessPolicy:
            BucketName: !Ref MessageStorage
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref MessageStorage
            Events: s3:ObjectCreated:*
  MessagesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: message_id 
        Type: String 
      ProvisionedThroughput:
        ReadCapacityUnits: 5 
        WriteCapacityUnits: 5 
      TableName: MessagesTable