AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  MessageStorage:
    Type: 'AWS::S3::Bucket'
  MessageHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: Lambda/messages
      Handler: messageHandler.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - SESCrudPolicy:
            IdentityName: "*"
        - !Ref SNSPubPolicy
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref MessageStorage
            Events: s3:ObjectCreated:*
  MessagesTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: 'message_id'
        Type: 'String'
      ProvisionedThroughput:
        ReadCapacityUnits: 5 
        WriteCapacityUnits: 5 
      TableName: 'MessagesTable'
      
      
  SNSPubPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SNSPubPolicy
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action: 'sns:Publish'
            Resource: "*"
